CREATE TABLE IF NOT EXISTS products (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) UNIQUE NOT NULL,
    summary TEXT,
    description TEXT,
    short_description TEXT,
    price INT NOT NULL DEFAULT 0,
    sale_price INT DEFAULT NULL,
    type VARCHAR(50) DEFAULT 'wordpress-plugin',
    product_code VARCHAR(100),
    version VARCHAR(50) DEFAULT '1.0.0',
    file_path VARCHAR(255),
    protected_file_path VARCHAR(255),
    license_type VARCHAR(50) DEFAULT 'lifetime',
    license_duration_days INT DEFAULT 365,
    max_activations INT DEFAULT 1,
    max_domains INT DEFAULT 1,
    allowed_domains TEXT,
    update_policy VARCHAR(50) DEFAULT 'all',
    changelog TEXT,
    release_notes TEXT,
    requirements TEXT,
    wp_version VARCHAR(20) DEFAULT '6.0',
    php_version VARCHAR(20) DEFAULT '8.2',
    author VARCHAR(100) DEFAULT 'EAFD',
    is_active TINYINT(1) DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
